# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- powershell: |
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      $results = Get-ChildItem -Recurse -Include *.ps1 | % { Invoke-ScriptAnalyzer -Path $_ -ExcludeRule PSAvoidUsingWriteHost } | Select-Object RuleName, Severity, ScriptPath, Line, Message
      if ($null -ne $results) {
        $results
        throw "$($results.count) PSScriptAnalyzer errors!"
      }
  displayName: PSScriptAnalyzer
