trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- powershell: |
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      Install-Module PSScriptAnalyzer -Scope CurrentUser
      $suppress = 'PSAvoidUsingConvertToSecureStringWithPlainText', 'PSAvoidUsingWriteHost'
      Invoke-ScriptAnalyzer -Path . -ExcludeRule $suppress -EnableExit
  displayName: PSScriptAnalyzer
