trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- powershell: |
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      $suppress = "PSAvoidUsingConvertToSecureStringWithPlainText", "PSAvoidUsingWriteHost"
      $results = Get-ChildItem -Recurse -Include *.ps1 | % { Invoke-ScriptAnalyzer -Path $_ -ExcludeRule $suppress } | Select-Object RuleName, Severity, ScriptPath, Line, Message
      if ($null -ne $results) {
        $results
        throw "$($results.count) PSScriptAnalyzer error(s)!"
      }
  displayName: PSScriptAnalyzer
